[package]
name = "randomushroom_plugin"
version = "0.1.0-dev"
edition = "2024"
license = "GPL-3.0-or-later"

[lib]
name = "randomushroom"
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true

[dependencies]
dllmain-rs = "0.1.0"
fn_abi = "3.0.0"
fn_type_alias = "0.1.0"
neohook = "0.13.1"
winsafe = { version = "0.0.28", features = ["user"] }
